### ISSUE TITLE
Stopped updating

### ISSUE THREAD

**Issue by adamchainz** [pre-commit/mirrors-jshint#10]
The [actions tab](https://github.com/pre-commit/mirrors-jshint/actions/workflows/main.yml) shows:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. 

So recent version 2.13.2 has not been picked up.

**Comment by asottile** [comment]
annoying github makes me click a button once a month to keep these running -- should be fixed now (I must have missed this one)

**Comment by adamchainz** [comment]
It sends a notification? Curious for my own mirror repos.

**Comment by asottile** [comment]
it's bugged for organizations, I have a long standing ticket with github

**Comment by asottile** [comment]
actually, I think the notification just doesn't work at all, I've noticed all my other things are stopped as well

**Comment by adamchainz** [comment]
Dang. I just set up a bimonthly calendar reminder for myself 🤷‍♂️
